# Mandatory settings

name: dtsbourg / Thoughts
paginate: 25
url: https://dtsbourg.github.io
blog_theme: light # Or use dark
baseurl: /thoughts
exclude: []

# Optional settings

about_enabled: false # Change to true if you wish to show an icon in the navigation that redirects to the about page
discus_identifier: # Add your Disqus identifier
ga_analytics: UA-65856095-1
local_fonts: false # Change to true if you wish to use local fonts
rss_enabled: true # Change to false if not
scrollappear_enabled: true # Change to false to disable
social:
  dribbble: # Add your Dribbble handle
  facebook: # Add your Facebook handle
  flickr: # Add your Flickr handle
  github: dtsbourg
  linkedin: dylan-bourgeois-319ab294
  twitter: dtsbourg
  email: # Add your Email address
  bitcoin: # Add your Bitcoin link or address

# Important settings (change at own risk)

assets:
  features:
    automatic_img_size: false
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/yarn
    - _assets/stylesheets/modules/_icons.scss
    - _assets/images/ico
    - _assets/images/pose-sketch
    - _assets/images/selu
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
exclude:
  - .travis.yml
  - bin/*
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - vendor/
  - yarn.lock
plugins:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
paginate_path: /posts/page/:num/
permalink: posts/:slug
